function at_export(statstemp,option)
% export cell cycle data generated by
global timeLapse

if numel(statstemp)==0
    return;
end

% save stats data generated by at_cellCycle

str=strcat(timeLapse.realPath,timeLapse.filename,'-stats-autotrack.mat');

if nargin==1 % append
    if exist(str)
        load(str);
        
        idx=checkRedundant(stats,statstemp);
        disp([num2str(length(idx)) ' to be written to stat file...']);
        
        %size(stats)
        %size(statstemp)
        
        if numel(idx)
            % size(stats), size(statstemp)
            stats=[stats; statstemp(idx,:)];
        end
    else
        stats=statstemp;
    end
else % overwrite
    if ischar(option)
    if strcmp(option,'overwrite')
        stats=statstemp;
    end
    else
      str=strcat(timeLapse.realPath,timeLapse.filename,'-pos',num2str(option),'-stats-autotrack.mat');
      stats=statstemp;
      
    end
end

save(str,'stats');

function iout=checkRedundant(stats,statstemp)

sstats=stats(:,1:5);
sstatstemp=statstemp(:,1:5);
[i ia ib]=intersect(sstats,sstatstemp,'rows');
iout=setdiff(1:size(statstemp,1),ib);






