function at_export(statstemp,path,convert,outlier)
% export cell cycle data generated by
global timeLapse

if numel(statstemp)==0
  %  return;
end

% save stats data generated by at_cellCycle


 if isa(path,'double')
<<<<<<< HEAD
      str=strcat(timeLapse.realPath,timeLapse.filename,'-pos',num2str(path),'-stats-autotrack-prod2.mat');
=======
     str=strcat(timeLapse.realPath,timeLapse.filename,'-pos',num2str(path),'-stats-autotrack-prod.mat')
>>>>>>> 993c798fc5dc576f7ea5b46a0e5a540a58563d50
     % prod if pod fluo x area to be considerered
 else
     str=path; 
 end
 
stats=statstemp;

if numel(userpath)==0
    localpath=pwd;
else
localpath=userpath;
localpath=localpath(1:end-1);
end

if nargin==4
    if isunix
save([localpath '/stats.mat'],'stats','outlier','convert');
eval(['!mv ' [localpath '/stats.mat'] ' ' str]);
    else
save(str,'stats','outlier','convert');        
    end
else
    if nargin==3
    if isunix
save([localpath '/stats.mat'],'stats','convert');
eval(['!mv ' [localpath '/stats.mat'] ' ' str]);
    else
 save(str,'stats','convert');          
    end
    
    else
      if isunix
save([localpath '/stats.mat'],'stats');
eval(['!mv ' [localpath '/stats.mat'] ' ' str]);
    else
 save(str,'stats');          
    end  
    end
  
end



function iout=checkRedundant(stats,statstemp)

sstats=stats(:,1:5);
sstatstemp=statstemp(:,1:5);
[i ia ib]=intersect(sstats,sstatstemp,'rows');
iout=setdiff(1:size(statstemp,1),ib);






